### ISSUE TITLE
I'm not sure it works anymore.

### ISSUE THREAD

**Issue by Sheshank-s** [kyleplo/scratch-timeline#2]
![image](https://user-images.githubusercontent.com/11379161/33049012-e4e32f70-ce12-11e7-8561-b217bb562ef8.png)
I have been seeing this image for the past 10 minutes lol

**Comment by radioblahaj** [comment]
Same Here. :P

**Comment by radioblahaj** [comment]
Hi

**Comment by kerrtravers** [comment]
@GreenBayRules Same here, the data must be very far away 😆

**Comment by radioblahaj** [comment]
lol @vutondesign

**Comment by kyleplo** [comment]
lol i think I know what is wrong.

**Comment by kyleplo** [comment]
Fixed!

**Comment by kerrtravers** [comment]
👍

**Comment by radioblahaj** [comment]
yay!
